[project]
authors = ["Jason Mercer <jasonjmercer@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "pyproj4de"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.13.*"
jupyterlab = ">=4.3.5,<5"
polars = ">=1.22.0,<2"
